language: php
cache:
  bundler: true
  apt: true
  directories:
  - vendor
php:
- 5.5
mysql:
  database: drupal
  username: root
  encoding: utf8
install:
- sudo apt-get update > /dev/null
- composer selfupdate
- mysql -e 'SET GLOBAL wait_timeout = 5400;'
- mysql -e "SHOW VARIABLES LIKE 'wait_timeout'"
- echo 'max_execution_time = 120' >> drupal.php.ini;
- echo 'sendmail_path = /bin/true' >> drupal.php.ini;
- phpenv config-add drupal.php.ini
- phpenv rehash
- composer global require drush/drush:6.*
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- git clone --branch 8.x-1.x http://git.drupal.org/project/composer.git ~/.drush/composer
- drush dl drupal --default-major=7 -y
- mv drupal-* drupal
- mv composer.json drupal/profiles/standard/.
- mkdir -p drupal/sites/all/modules/contrib/lightning_features
- mv lightning_* drupal/sites/all/modules/contrib/lightning_features/.
- ls -l
- cd drupal
- drush make --no-core sites/all/modules/contrib/lightning_features/lightning_features.make -y
- drush si standard --db-url=mysql://root:@localhost/drupal -y
before_script:
- drush en lightning_* -y
- drush dis dblog -y
- drush cc all
- drush runserver --server=builtin 8080 &
- until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do sleep 0.2; done
script:
- drush uli -l http://127.0.0.1:8080 -v
matrix:
  fast_finish: true
notifications:
  slack:
    secure: g1Uzxs0sKhsqC+/V+I8xYkysVVYRrn9H/mS9xRT1xWaPX+NIGk4SJpdlHNbiI9oqbkI7H+QjD337q2QKhIqRshXrwRVUFo9pGl8NOsQW04iW5Uc7nE7Xdpao6JZbrh9FAWZfZeJOlDi/ojDJhyQNSYdMfLlAiI/1dmbVsks018zqsj9rzBcTsl0NkwImbnoRmbs2uol6M71nm7R3+Fisr37OnQ8NEERRUShWolGboN3cfI1SnM8nI1IahIqM1Gp7lJdh/ku12Jwj/WmT3UQ3OqQRB5SR1UeFQ+Hn+O6UH2quxF4cnrdETaMuZauvt3+/3D/ye4hxt1bWrlBQimuJPGRAZLLG5aySHBMMYKojrbWQKuarILdrV7M+FaTC+J1HetnEJGR7eC+os+faDwAE7+92AxCjno/vd6HpC8oslJFA1Qs7jlRyVgoDmYj0ikOse03cw3lCenJwrFgILyWRDbJE55j7ZwISjKRdM6seYsR6h5UJ1E0PhAw9iiYw6HEn1Qq8Fy3+fYAgNni45Hlsk3ykmSBVomUpbceeTAnw4EU5HB1lKQU+ZlMTWUF3TiL75tMKrmjgzk7sHLHlI7cK1J30S1P8CANkcA/CWNChoeojb9NbbUaomv+ChjkawHyRLwaSxKOLyuuOmnCyxfO2ovCGw0z/kluJlLjpau9mabc=
