language: php
php:
- 5.4
before_install:
- wget https://raw.githubusercontent.com/jonkemp/qunit-phantomjs-runner/master/runner.js
script:
- phantomjs runner.js qunit/core_personalization.html
- phantomjs runner.js acquia_lift_profiles/qunit/test.html
- phantomjs runner.js qunit/acquia_lift_target.html
- phantomjs runner.js qunit/administration.html
notifications:
  slack:
    secure: mpS7oDoOBsl7KlQUY9loYd1gUiozp4D8kc3vl0nVkm8N8SpAR0RYplPHY/5Jtesbl73kWG4vV7UURNct0cc+szm0eLVbCFcS6vq6evzPKdHzl0U2YiFCLsJItDXBYhDDb5bY4yZgCY8zUBmnOM/S3NysxMMcNmU/DaqUvhZWnGU=
